typography_spectrum: 0.49482
color:
  brandColors:
    - '#1774a0'
    - '#a6ce39'
    - '#000000'
    - '#00ffff'
    - '#ffffff'
  brandStrength: 0.5
  lightness: 0.8306354689411819
  saturation: 0.2508599688299
  rhythmicContrast: 0.095735291717574
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.790985498111695
analytics:
  google: null
  facebook: null
  twitter: null
name: ANOTEC
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: anotec environmental
description: stick our nose in your business
purpose: []
