layout_spectrum: 0.5600658175345548
typography_spectrum: 0.8323847749539752
color:
  saturation: 0.7762305005659156
  brandStrength: 0.9383207732924067
  lightness: 0.53831983436941
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  rhythmicContrast: 0.9950806602818135
coverPrefs:
  filter: false
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: >-
    2/112 Dunheved Circuit St Marys 2760 NSW Australia   service@anotec.com.au 
    john zavras 
  email: john@anotec.com.au
  url: 'http://anotec.com.au'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/54bde917-b1ac-486f-9e2e-7b79e178eac3.jpg
name: 'Anotec Environmental '
url: 'https://thegrid.ai/anotec'
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: ABOUT US
    id: 8e789427-bb1d-4784-b182-13e4246552e4
    type: content
  - name: Odour Control
    id: 68da98c8-b660-4265-8a3d-0de96e44dd65
    type: content
  - name: 'Safety Data '
    id: cf55e2ff-1719-4f4d-a333-3c36e9c49b89
    type: content
  - name: Contact Us
    id: daabb6ca-b757-4121-a3e3-0ad913899025
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5dfb51ad-b63c-4d48-baef-f416cf30ccb9.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Anotec Environmental
content: []
description: solutions for you
purpose:
  - type: contact
    url: 'tel:0297001222'
    label: Call 02 9700 1222
  - type: contact
    url: 'mailto:service@anotec.com.au'
    label: Contact us
