layout_spectrum: 0.3468452341694127
typography_spectrum: 0.3172186238658015
color:
  saturation: 0.9596759023075683
  brandStrength: 0.3913557648572075
  lightness: 0.7216347406994514
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  rhythmicContrast: 0.33472299983992365
coverPrefs:
  filter: false
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: '2/112 Dunheved Circuit St Marys 2760 NSW Australia   service@anotec.com.au '
  email: john@anotec.com.au
  url: 'http://anotec.com.au'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/54bde917-b1ac-486f-9e2e-7b79e178eac3.jpg
name: 'Anotec Environmental '
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: ABOUT US
    id: 8e789427-bb1d-4784-b182-13e4246552e4
    type: content
  - name: R & D
    id: 1b23e760-0a23-4d5d-8c14-b5bc894ff967
    type: content
  - name: Odour Control
    id: 68da98c8-b660-4265-8a3d-0de96e44dd65
    type: content
  - name: 'GECA '
    id: 2d16c497-d235-45c1-83af-4b56e3f70a57
    type: content
  - name: Chemicals
    id: a8bfcb3f-bd3f-4ac9-a4ab-457f95411395
    type: content
  - name: 'Services '
    id: 10e6fe10-49ec-4a50-8792-e4b1251f5104
    type: content
  - name: 'Safety Data '
    id: cf55e2ff-1719-4f4d-a333-3c36e9c49b89
    type: content
  - name: Sentinel
    id: 9ce2765c-7969-4bb0-830a-ab15e7219fda
    type: content
  - name: Applications
    id: aee7b2ae-ed6b-46c7-9a7e-7616053428bd
    type: content
  - name: 'Sell for Us '
    id: b0a04383-8008-4e14-a373-0c45e96cd6cb
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5dfb51ad-b63c-4d48-baef-f416cf30ccb9.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Anotec Environmental
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FaocpnfyoYBk%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DaocpnfyoYBk&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FaocpnfyoYBk%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'https://youtu.be/aocpnfyoYBk'
      keywords:
        - anotec
        - duration
        - fogmaster
        - zavras
        - skipo
        - dabaw
        - haba
        - views
        - odour
        - autoplay
      related: []
      author:
        - name: John Zavras
          url: 'https://www.youtube.com/user/alky123'
          avatar: {}
      '@context': 'http://schema.org'
      title: 'http://anotec.com.au'
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=aocpnfyoYBk&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=aocpnfyoYBk&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=aocpnfyoYBk&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=aocpnfyoYBk&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=aocpnfyoYBk&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=aocpnfyoYBk'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=aocpnfyoYBk
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=aocpnfyoYBk
          package: '544007664'
          namespace: google
          type: ios
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      description: ''
      inLanguage: en
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: solutions for you
purpose:
  - type: contact
    url: 'tel:0297001222'
    label: Call 02 9700 1222
  - type: contact
    url: 'mailto:service@anotec.com.au'
    label: Contact us
url: 'https://thegrid.ai/anotec'
