typography_spectrum: 0.7518243679988871
content_rating:
  adult: false
color:
  lightness: 0.07187174894496579
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  saturation: 0.43360413486977095
  brandStrength: 0.23445747541005513
  rhythmicContrast: 0.27744282678783977
github: true
opengraph: {}
layout_spectrum: 0.6790474465488466
analytics:
  google: UA-97060531-1
author:
  name: >-
    2/112 Dunheved Circuit St Marys 2760 NSW Australia   service@anotec.com.au 
    John Zavras 
  url: 'http://anotec.com.au'
  email: john@anotec.com.au
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/54bde917-b1ac-486f-9e2e-7b79e178eac3.jpg
name: 'Anotec Environmental '
url: 'https://thegrid.ai/anotec'
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: About Us
    id: 8e789427-bb1d-4784-b182-13e4246552e4
    type: content
  - name: Contact Us
    id: daabb6ca-b757-4121-a3e3-0ad913899025
    type: content
  - name: 'Safety Data '
    id: cf55e2ff-1719-4f4d-a333-3c36e9c49b89
    type: content
  - name: Odour Control
    id: 68da98c8-b660-4265-8a3d-0de96e44dd65
    type: content
  - name: Order Now
    id: 8ac02e7c-ac96-4c00-b46e-48b941fd4f2d
    type: content
  - name: Raw Materials
    id: 657107fc-abe7-4fb7-99a9-0fcb8c6a675e
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f226b0bc-a6ed-4645-82d5-4eb52d34da70.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Anotec Environmental Pty Ltd
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=http%3A%2F%2Fwww.youtube.com%2Fembed%2Fdaovv-wEcrU&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Ddaovv-wEcrU&image=http%3A%2F%2Fi.ytimg.com%2Fvi%2Fdaovv-wEcrU%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - avatar: {}
      related: []
      publisher:
        url: 'http://youtube.com'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: youtu.be
      keywords:
        - ''
      description: Uploaded by None on 2018-01-22.
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=daovv-wEcrU&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=daovv-wEcrU&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=daovv-wEcrU&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=daovv-wEcrU&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=daovv-wEcrU&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=daovv-wEcrU'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=daovv-wEcrU
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=daovv-wEcrU
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/daovv-wEcrU'
      title: Chemical Laboratory
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=http%3A%2F%2Fwww.youtube.com%2Fembed%2Fdaovv-wEcrU&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Ddaovv-wEcrU&image=http%3A%2F%2Fi.ytimg.com%2Fvi%2Fdaovv-wEcrU%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - avatar: {}
      related: []
      publisher:
        url: 'http://youtube.com'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: youtu.be
      keywords:
        - ''
      description: Uploaded by None on 2018-01-22.
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=daovv-wEcrU&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=daovv-wEcrU&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=daovv-wEcrU&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=daovv-wEcrU&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=daovv-wEcrU&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=daovv-wEcrU'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=daovv-wEcrU
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=daovv-wEcrU
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/daovv-wEcrU'
      title: Chemical Laboratory
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
coverPrefs:
  filter: false
description: sustainable solutions
purpose:
  - type: contact
    url: 'tel:0297001222'
    label: Call 02 9700 1222
  - type: contact
    url: 'mailto:service@anotec.com.au'
    label: Contact us
