layout_spectrum: 0.9177814482968523
typography_spectrum: 0.36478431432839886
color:
  saturation: 0.13777360813295708
  brandStrength: 0.4698545075979748
  lightness: 0.38743649473487596
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  rhythmicContrast: 0.8566484875912492
coverPrefs:
  filter: false
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: John Zavras
  email: john@anotec.com.au
  url: 'http://anotec.com.au'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/54bde917-b1ac-486f-9e2e-7b79e178eac3.jpg
name: 'Anotec Environmental '
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: ABOUT US
    id: 8e789427-bb1d-4784-b182-13e4246552e4
    type: content
  - name: R & D
    id: 1b23e760-0a23-4d5d-8c14-b5bc894ff967
    type: content
  - name: 'Products '
    id: 68da98c8-b660-4265-8a3d-0de96e44dd65
    type: content
  - name: 'GECA Approval '
    id: 2d16c497-d235-45c1-83af-4b56e3f70a57
    type: content
  - name: 'Services '
    id: 10e6fe10-49ec-4a50-8792-e4b1251f5104
    type: content
  - name: 'Safety Data '
    id: cf55e2ff-1719-4f4d-a333-3c36e9c49b89
    type: content
  - name: applications
    id: 3d13138c-2f45-4ba1-9988-6ff8cbfc9c24
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5dfb51ad-b63c-4d48-baef-f416cf30ccb9.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Anotec Environmental
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FaocpnfyoYBk%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DaocpnfyoYBk&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FaocpnfyoYBk%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: John Zavras
          url: 'https://www.youtube.com/user/alky123'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      keywords:
        - anotec
        - duration
        - fogmaster
        - zavras
        - skipo
        - dabaw
        - haba
        - views
        - odour
        - autoplay
      description: ''
      inLanguage: en
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=aocpnfyoYBk&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=aocpnfyoYBk&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=aocpnfyoYBk&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=aocpnfyoYBk&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=aocpnfyoYBk&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=aocpnfyoYBk'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=aocpnfyoYBk
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=aocpnfyoYBk
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/aocpnfyoYBk'
      title: 'http://anotec.com.au'
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: solutions for you
purpose:
  - type: contact
    url: 'tel:0297001222'
    label: Call 02 9700 1222
  - type: contact
    url: 'mailto:service@anotec.com.au'
    label: Contact us
